<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
					xmlns:tns="http://webservice.believeus.cn" 
					xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
					xmlns:xsd="http://www.w3.org/2001/XMLSchema"
					name="UserService" 
					targetNamespace="http://webservice.believeus.cn">
  <wsdl:types>
  <!-- wsimport 会根据这个文档生成相应的方法和方法的返回值 -->
    <xsd:schema targetNamespace="http://webservice.believeus.cn">
			<xsd:include schemaLocation="user.xsd"/>
		<!-- <xsd:import namespace="http://webservice.believeus.cn" schemaLocation="user.xsd"/>   -->
		<!-- Begin :Name:wuqiwei Date:2013-07-22 AddReason 只有用element声明才能被外界使用 -->
    </xsd:schema>
  </wsdl:types>
  <!-- 声明一个可以传递的消息getUserByHQL,声明才能被使用-->
  <!-- 注意该name必须和方法名一致并需要添加Response -->
  <wsdl:message name="getUserByHQLResponse">
    <wsdl:part element="tns:getUserByHQLResponse" name="parameters"/>
  </wsdl:message>
  <!-- 声明一个可以传递的消息getUserByHQLResponse,声明才能被使用 -->
  <!-- 注意该name必须和方法名一致 -->
  <wsdl:message name="getUserByHQL">
  	<wsdl:part element="tns:getUserByHQL" name="parameters" />
  </wsdl:message>
  <!-- 定义一个外界可以访问的接口IUserService -->
  <wsdl:portType name="IUserService">
  	<!-- 定义暴露的方法名 wsimport会根据getUserByHQL生成方法名-->
    <wsdl:operation name="getUserByHQL">
      <wsdl:input message="tns:getUserByHQL"/>
      <wsdl:output message="tns:getUserByHQLResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <!--  Binding元素将portType元素和operation元素赋给一个特殊的协议和编码样式 -->
  <!-- 定义方法数据传递的协议转换器 -->
  <wsdl:binding name="IUserServiceSOAP" type="tns:IUserService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <!-- getUserByHQL是type="tns:IUserService"中的方法 -->
    <wsdl:operation name="getUserByHQL">
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <!-- service元素负责将传递的Internet地址赋给一个具体协议的绑定 -->
   <!-- 定义一个访问的入口,该入口通过http://www.believeus.cn/webservice发送和接收数据 -->
  <!-- 接收数据经过tns:IUserServiceSOAP将数据转换成相关的协议进行传输 -->
  <!-- 同理，当输出数据时也必须要经过tns:IUserServiceSOAP,然后从http://www.believeus.cn/webservice发送出去 -->
  <wsdl:service name="UserService">
    <wsdl:port binding="tns:IUserServiceSOAP" name="webserviceSOAP">
      <soap:address location="http://www.believeus.cn/ns/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
<!-- 根据该文档生成相关的类命令  -->
<!--服务端 wsimport -d 存放的目录 -keep webservice.wsdl -->
<!-- 客户端  -->